### ISSUE TITLE
About screen capture

### ISSUE THREAD

**Issue by suxragi** [charlie0129/bitrate-visualizer#2]
Only the displayed screen is captured and saved as an image, but I would like it to be possible to capture the waveform of an entire song.

**Comment by charlie0129** [comment]
Hi. I've been busy for the entire month. Sorry for the late reply. Here are some updates:

- The ability to save the bitrate of the entire song has been implemented in v0.2.0 !
- Running on Windows 7 is unfortunately not possible or hard to implement.

**Comment by suxragi** [comment]
Thank you for your prompt response despite your busy schedule.
The entire image can now be captured, further improving the usability of the tool.

**Comment by charlie0129** [comment]
Feel free to reopen or further comment on this issue if you have more questions :)
